site syndication: fix TypeError when site_rss_items value is None.
I ran `black` as well.  The real change is on this line:

    items = list(record.value) if record.value else ()

Traceback:

```
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp310/Products.CMFPlone-6.0.7rc1-py3.10.egg/Products/CMFPlone/MigrationTool.py", line 289, in upgrade
    step["step"].doStep(setup)
  File "/Users/maurits/shared-eggs/cp310/Products.GenericSetup-3.0.1-py3.10.egg/Products/GenericSetup/upgrade.py", line 193, in doStep
    self.handler(tool)
  File "/Users/maurits/shared-eggs/cp310/plone.app.upgrade-3.0.7-py3.10.egg/plone/app/upgrade/v60/final.py", line 183, in fix_syndication_settings
    items = list(record.value)
TypeError: 'NoneType' object is not iterable
```